### ISSUE TITLE
Exception in uploading to Azure

### ISSUE THREAD

**Issue by monaka** [deis/wal-e#13]
This is moved from deis/postgres#119.

It show exception like this when WAL-E uploads WAL.
I tried it at "Japen East" and "Asia East" and 100% reproduction.

WALs seems be uploaded even though sxception messages are shown.
(I've not check their content. Possibly broken.)

```
LOG:  archive command failed with exit code 2
DETAIL:  The failed archive command was: envdir "/etc/wal-e.d/env" wal-e wal-push pg_xlog/000000010000000000000001
wal_e.main   INFO     MSG: starting WAL-E
        DETAIL: The subcommand is "wal-push".
        STRUCTURED: time=2016-06-21T06:02:50.569363-00 pid=169
wal_e.worker.upload INFO     MSG: begin archiving a file
        DETAIL: Uploading "pg_xlog/000000010000000000000001" to "wabs://database/wal_005/000000010000000000000001.lzo".
        STRUCTURED: time=2016-06-21T06:02:50.837310-00 pid=169 action=push-wal key=wabs://database/wal_005/000000010000000000000001.lzo prefix= seg=000000010000000000000001 state=begin
requests.packages.urllib3.connectionpool INFO     Starting new HTTPS connection (1): monadeis0canary.blob.core.windows.net
wal_e.main   CRITICAL MSG: An unprocessed exception has avoided all error handling
        DETAIL: Traceback (most recent call last):
          File "/usr/local/lib/python2.7/dist-packages/wal_e/cmd.py", line 610, in main
            concurrency=args.pool_size)
          File "/usr/local/lib/python2.7/dist-packages/wal_e/operator/backup.py", line 285, in wal_archive
            group.join()
          File "/usr/local/lib/python2.7/dist-packages/wal_e/worker/pg/wal_transfer.py", line 135, in join
            val = self.wait_change.get()
          File "/usr/local/lib/python2.7/dist-packages/gevent/queue.py", line 571, in get
            return waiter.get()
          File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 875, in get
            return self.hub.switch()
          File "/usr/local/lib/python2.7/dist-packages/gevent/hub.py", line 606, in switch
            return greenlet.switch(self)
        LoopExit: ('This operation would block forever', <Hub at 0x7f7dc23caaf0 epoll default pending=0 ref=0 fileno=9>)

        STRUCTURED: time=2016-06-21T06:02:51.367364-00 pid=169
```

**Comment by monaka** [comment]
Maybe I fixed this. I'm testing on my environment now. I'll re-push the patch to #12 later.

**Comment by monaka** [comment]
This issue has been reproduced on my cluster. And it works after applying PR #12.
Does anyone run official deis/postgres images correctly with Azure blobs?

**Comment by monaka** [comment]
Note: I moved my environment on Azure to #18 based. It is more stable than #12.
